name: daftar_restoran
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.3.2"
dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_screenutil: ^5.5.3+2
  fluentui_system_icons: ^1.1.176
  flutter_svg: ^1.1.1+1
  google_fonts: ^3.0.1
  get: ^4.6.5
  hexcolor: ^2.0.7
  cached_network_image: ^3.2.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/local_restaurant.json